name: Check coding style
on: [push, pull_request]
jobs:
  linter:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jidicula/clang-format-action@v4.15.0
      with:
        clang-format-version: '20'
        check-path: '.'

    - name: install clang-tidy
      run: sudo apt install -y clang-tidy
    - name: gen makefile
      run: cmake -S. -Bbuild
    - name: build proj to gen compile_commands.json
      run: cmake --build build
    - name: run clang-tidy
      run: clang-tidy -p build ./housing.cpp
