name: Check coding style
on: [push, pull_request]
jobs:
  clangtools:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          style: 'file'  # Use .clang-format config file
          tidy-checks: '' # Use .clang-tidy config file
          step-summary: true
    - name: Fail fast?!
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1
